INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('testKey', 'testWert');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('testModus', 'true');
--AENDERUNGSSATZ
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('aenderungssatz', '0.03');
--TIMER-INTERVALL in Minuten
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('timerIntervall', '1');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('intervallBeobachtung', '2');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('intervallTradeAktion', '3');
--BINANCE-API
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('binanceURL', 'https://api.binance.com/api/v1');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('binancePing', '/ping');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('binanceLetztePreise', '/ticker/allPrices');
--MAIL-Einstellungen
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailBenachrichtigung', 'false');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailHost', 'smtp.gmail.com');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailPort', '587');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailSenderUser', 'test@mail.com');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailSenderPass', 'XXX');
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('mailEmpfaenger', 'test@mail.com');
--REPORT-Einstellungen
INSERT INTO CRYPTOBOT_CONFIG(KEY, VALUE) VALUES ('reportBetreff', 'CRYPTOBOT-REPORT: ');