--KAUF
INSERT INTO SIMPEL_TRADEJOB(SIMPEL_TRADEJOB_PK, CRYPTOWAEHRUNG , CRYPTOWAEHRUNG_REFERENZ, ERSTELLTAM , ERLEDIGTAM, AKTION, MENGE, KAUFWERT, ZIELWERT, LETZTWERT, SPITZENWERT, TRADE_STATUS, PLATTFORM, GANZ_ZAHLIG)
VALUES (101, 'LTC', 'BTC', SYSTIMESTAMP, NULL, 'K', 0.001, 0.005, 0.004, 0.006, null, 'ERSTELLT', 'BIC', '0');
INSERT INTO SIMPEL_TRADEJOB(SIMPEL_TRADEJOB_PK, CRYPTOWAEHRUNG , CRYPTOWAEHRUNG_REFERENZ, ERSTELLTAM , ERLEDIGTAM, AKTION, MENGE, KAUFWERT, ZIELWERT, LETZTWERT, SPITZENWERT, TRADE_STATUS, PLATTFORM, GANZ_ZAHLIG)
VALUES (102, 'XVG', 'BTC', SYSTIMESTAMP , SYSTIMESTAMP, 'K', 300.00005, 0.00005234, 0.00002234, 0.00001234, null, 'ABGESCHLOSSEN', 'BIC','1');
--VERKAUF
INSERT INTO SIMPEL_TRADEJOB(SIMPEL_TRADEJOB_PK, CRYPTOWAEHRUNG , CRYPTOWAEHRUNG_REFERENZ, ERSTELLTAM , ERLEDIGTAM, AKTION, MENGE, KAUFWERT, ZIELWERT, LETZTWERT, SPITZENWERT, TRADE_STATUS, PLATTFORM, GANZ_ZAHLIG)
VALUES (501, 'LTC', 'BTC', SYSTIMESTAMP, NULL, 'V', 0.001, 0.005, 0.006, 0.004, null, 'ERSTELLT', 'BIC', '0');
INSERT INTO SIMPEL_TRADEJOB(SIMPEL_TRADEJOB_PK, CRYPTOWAEHRUNG , CRYPTOWAEHRUNG_REFERENZ, ERSTELLTAM , ERLEDIGTAM, AKTION, MENGE, KAUFWERT, ZIELWERT, LETZTWERT, SPITZENWERT, TRADE_STATUS, PLATTFORM, GANZ_ZAHLIG)
VALUES (502, 'XVG', 'BTC', SYSTIMESTAMP , SYSTIMESTAMP, 'V', 300.00005, 0.00001234, 0.00002234, 0.00003234, null, 'ABGESCHLOSSEN', 'BIC','1');