INSERT INTO TIMERJOB(TIMERJOB_PK, BEZEICHNUNG , ERSTELLTAM , LETZTE_DURCHFUEHRUNG, NAECHSTE_DURCHFUEHRUNG) VALUES (1, 'TRADE_BEOBACHTUNG', SYSTIMESTAMP, SYSTIMESTAMP, null);
INSERT INTO TIMERJOB(TIMERJOB_PK, BEZEICHNUNG , ERSTELLTAM , LETZTE_DURCHFUEHRUNG, NAECHSTE_DURCHFUEHRUNG) VALUES (2, 'TRADE_AKTION', SYSTIMESTAMP, SYSTIMESTAMP, null);
