CREATE SEQUENCE CRYPTOWAEHRUNG_SQ START WITH 200000 INCREMENT BY 1;
CREATE SEQUENCE TRADEAKTION_SQ START WITH 200000 INCREMENT BY 1;
CREATE TABLE CRYPTOWAEHRUNG (TRADEAKTION_PK BIGINT NOT NULL, BEZEICHNUNG VARCHAR(255) NOT NULL, GUELTIG CHAR(1) NOT NULL, KURZBEZEICHNUNG VARCHAR(255) NOT NULL, PRIMARY KEY (TRADEAKTION_PK));
CREATE TABLE PROPERTIES (KEY VARCHAR(255) NOT NULL, VALUE VARCHAR(255) NOT NULL, PRIMARY KEY (KEY));
CREATE TABLE TRADEAKTION (TRADEAKTION_PK BIGINT NOT NULL, CRYPTOWAEHRUNG VARCHAR(255) NOT NULL, ERLEDIGTAM TIMESTAMP, ERSTELLTAM TIMESTAMP NOT NULL, KAUFWERT NUMERIC NOT NULL, LETZTWERT NUMERIC, MENGE NUMERIC NOT NULL, CRYPTOWAEHRUNG_REFERENZ VARCHAR(255) NOT NULL, STATUS VARCHAR(255) NOT NULL, PLATTFORM VARCHAR(255) NOT NULL, ZIELWERT NUMERIC, PRIMARY KEY (TRADEAKTION_PK));
